# nixpacks.toml - EN LA RAÍZ
[phases.setup]
nixPkgs = [
    "postgresql",      # ← Esto instala libpq
    "gcc",
    "python311",
    "python3Packages.pip",
    "zlib",
    "libffi",
    "openssl"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate --noinput && gunicorn supportFlow.wsgi --bind 0.0.0.0:$PORT"