# Generated by Django 5.2.7 on 2026-01-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_categoria_ticket_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-created'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
