# Generated by Django 6.0.1 on 2026-01-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
