# Generated by Django 6.0.1 on 2026-01-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
